version: "3"
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - net1

  hydro-serving-manager:
    image: hydro-serving/manager:1.0-SNAPSHOT
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zipkin
    labels:
      - runtimeType=manager
      - httpPort=8080
      - appHttpPort=9090
    environment:
      SWARM_NETWORK_NAME: "net1"
      ZIPKIN_ENABLED: "true"
      ZIPKIN_HOST: "zipkin"
      MANAGER_EXPOSED_HOST: "hydro-serving-manager"
      MANAGER_SERVICE_NAME: "hydroserving_hydro-serving-manager"
      GATEWAY_SERVICE_NAME: "hydroserving_hydro-serving-gateway"
      REPOSITORY_SERVICE_NAME: "hydroserving_hydro-serving-repository"
    networks:
      - net1

  hydro-serving-gateway:
    image: hydro-serving/gateway:1.0-SNAPSHOT
    ports:
      - "8081:8080"
    depends_on:
      - zipkin
      - hydro-serving-manager
    labels:
      - runtimeType=gateway
      - httpPort=8080
      - appHttpPort=9090
    environment:
      ZIPKIN_ENABLED: "true"
      ZIPKIN_HOST: "zipkin"
      MANAGER_HOST: "hydro-serving-manager"
    networks:
      - net1

  hydro-serving-repository:
    image: hydro-serving/repository:1.0-SNAPSHOT
    ports:
      - "8082:8080"
    depends_on:
      - zipkin
      - hydro-serving-manager
    labels:
      - runtimeType=repository
      - httpPort=8080
      - appHttpPort=9090
    environment:
      ZIPKIN_ENABLED: "true"
      ZIPKIN_HOST: "zipkin"
      MANAGER_HOST: "hydro-serving-manager"
    volumes:
      - ${MODEL_DIRECTORY}:/models
    networks:
      - net1
networks:
  net1:
    external: true