version: "3"
services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "docker"
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
    networks:
      - net1

  hydro-serving-manager:
    image: hydro-serving/manager:0.0.1
    ports:
      - "8080:8080"
      - "8082:8082"
      - "9090:9090"
    depends_on:
      - postgres
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SWARM_NETWORK_NAME: "net1"
      ADVERTISED_MANAGER_HOST: "hydro-serving-manager"
      DATABASE_HOST: "postgres"
      HS_SERVICE_ID: "-20"
      APP_HTTP_PORT: "9090"
      SIDECAR_HTTP_PORT: "8080"
    networks:
      - net1
    labels:
      HS_SERVICE_MARKER: "HS_SERVICE_MARKER"
      hydroServingServiceId: "-20"
    deploy:
      labels:
        HS_SERVICE_MARKER: "HS_SERVICE_MARKER"
        hydroServingServiceId: "-20"

  hydro-serving-gateway:
    image: hydro-serving/gateway:0.0.1
    ports:
      - "8180:8080"
      - "8182:8082"
      - "9190:9090"
    depends_on:
      - hydro-serving-manager
      - postgres
    environment:
      MANAGER_HOST: "hydro-serving-manager"
      HS_SERVICE_ID: "-10"
      APP_HTTP_PORT: "9090"
      SIDECAR_HTTP_PORT: "8080"
    networks:
      - net1
    labels:
      HS_SERVICE_MARKER: "HS_SERVICE_MARKER"
      hydroServingServiceId: "-10"
    deploy:
      labels:
        HS_SERVICE_MARKER: "HS_SERVICE_MARKER"
        hydroServingServiceId: "-10"

networks:
  net1:
    external: true